"""add idempotency records

Revision ID: 9c25cf89f3a7
Revises: f24d45247968
Create Date: 2026-08-29 13:52:48.635321
"""
from alembic import op
import sqlalchemy as sa


revision = '9c25cf89f3a7'
down_revision = 'f24d45247968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
